### PR TITLE
tests: add simple gfapi access test

### PR DESCRIPTION
**Pull request by pkalever**
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@lxbsz @amarts please review. Thanks!

**Comment by lxbsz** [comment]
@pkalever 
Is it possible to add the truncate API testing at the same time ? Or will it be added together with READ/WRITE/.... in other separate test files ?

Currently I hit one crash issue for the glusterfs' 7dev/upstream newest code for the glfs_init(), when the glusterd service is stopped or the volume is not up or the volume is not exist.  And the reproducing frequency is around 5%.

Just for the case above, how about increasing the test times and adding more cases, such as for the none exist volume case ?

Thanks.

**Comment by pkalever** [comment]
> @pkalever
> Is it possible to add the truncate API testing at the same time ? Or will it be added together with READ/WRITE/.... in other separate test files ?

Yeah, That was my intention too. To extend this test for some practical IO calls (like read/write/Stat/zerofill/seek/[set/get]xattr/) and other api's we use at gluster-block and tcmu-runner.

@lxbsz Feel free to take over and submit a PR if you want.

> 
> Currently I hit one crash issue for the glusterfs' 7dev/upstream newest code for the glfs_init(), when the glusterd service is stopped or the volume is not up or the volume is not exist. And the reproducing frequency is around 5%.

I see!


> 
> Just for the case above, how about increasing the test times and adding more cases, such as for the none exist volume case ?

I expect the glfs_init to fail in case of volume not present. If that is not happening, then the later API's will eventually fail, like in creat/open ... etc.

As I mentioned in the commit msg, this is one simple gfapi access test to start with.

Thanks for your thoughts.

**Comment by lxbsz** [comment]
> > @pkalever
> > Is it possible to add the truncate API testing at the same time ? Or will it be added together with READ/WRITE/.... in other separate test files ?
> 
> Yeah, That was my intention too. To extend this test for some practical IO calls (like read/write/Stat/zerofill/seek/[set/get]xattr/) and other api's we use at gluster-block and tcmu-runner.

That's cool.

> 
> @lxbsz Feel free to take over and submit a PR if you want.
Yeah sure.

**Comment by pkalever** [comment]
> What is the goal of this PR? Ie, this is testing something in glusterfs, why should it matter for gluster-block?

Very good question @amarts!

Some of our users are having trouble setting up the gluster volume and they are using wrong IP's with gluster-block create cli and reporting issues saying block create fails.

See: https://github.com/gluster/gluster-block/issues/187#issuecomment-478008723

For such folks, this test case should help validate that underline storage is setup correctly and the gfapi access doesn't have any issues in their environment.

Hope that make-sense!
Thanks.

**Comment by pkalever** [comment]
> Got it, makes sense! These are very required in the project.
> 
> I ideally recommend having them in 'tools/', but its OK to be in tests/ also, and we should make sure to ship this one with RPM, so people can run this in their setup.

I don't mind creating a new directory with name tools and move gfapi_test.c into it.
Also I like the idea that we need to package this too. But should include this tools as part of the same gluster-block rpm package or should we get some inspiration from glusterfs who used to do package regression-tests ( all tests) as a separate rpm (http://rpmfind.net/linux/rpm2html/search.php?query=glusterfs-regression-tests)

```
[root@Fedora-Server ~]# rpm -qlp glusterfs-regression-tests-3.5.2-8.mga5.i586.rpm  | grep -v bugs
warning: glusterfs-regression-tests-3.5.2-8.mga5.i586.rpm: Header V3 RSA/SHA1 Signature, key ID 80420f66: NOKEY
/usr/share/glusterfs/run-tests.sh
/usr/share/glusterfs/scripts
/usr/share/glusterfs/scripts/generate-gfid-file.sh
/usr/share/glusterfs/scripts/get-gfid.sh
/usr/share/glusterfs/scripts/gsync-sync-gfid
/usr/share/glusterfs/scripts/gsync-upgrade.sh
/usr/share/glusterfs/scripts/post-upgrade-script-for-quota.sh
/usr/share/glusterfs/scripts/pre-upgrade-script-for-quota.sh
/usr/share/glusterfs/scripts/slave-upgrade.sh
/usr/share/glusterfs/tests
/usr/share/glusterfs/tests/README.md
/usr/share/glusterfs/tests/afr.rc
/usr/share/glusterfs/tests/basic
/usr/share/glusterfs/tests/basic/afr
/usr/share/glusterfs/tests/basic/afr/resolve.t
/usr/share/glusterfs/tests/basic/bd.t
/usr/share/glusterfs/tests/basic/cdc.t
/usr/share/glusterfs/tests/basic/file-snapshot.t
/usr/share/glusterfs/tests/basic/gfid-access.t
/usr/share/glusterfs/tests/basic/mount.t
/usr/share/glusterfs/tests/basic/nufa.t
/usr/share/glusterfs/tests/basic/posixonly.t
/usr/share/glusterfs/tests/basic/pump.t
/usr/share/glusterfs/tests/basic/quota.t
/usr/share/glusterfs/tests/basic/self-heald.t
/usr/share/glusterfs/tests/basic/volume-status.t
/usr/share/glusterfs/tests/basic/volume.t
/usr/share/glusterfs/tests/cluster.rc
/usr/share/glusterfs/tests/dht.rc
/usr/share/glusterfs/tests/fallocate.rc
/usr/share/glusterfs/tests/features
/usr/share/glusterfs/tests/features/glupy.t
/usr/share/glusterfs/tests/features/readdir-ahead.t
/usr/share/glusterfs/tests/fileio.rc
/usr/share/glusterfs/tests/include.rc
/usr/share/glusterfs/tests/nfs.rc
/usr/share/glusterfs/tests/performance
/usr/share/glusterfs/tests/performance/open-behind.t
/usr/share/glusterfs/tests/performance/quick-read.t
/usr/share/glusterfs/tests/utils
/usr/share/glusterfs/tests/utils/create-files.py
/usr/share/glusterfs/tests/utils/create-files.pyc
/usr/share/glusterfs/tests/utils/create-files.pyo
/usr/share/glusterfs/tests/volume.rc
```

If we decide to package this, then may be we need to wait for some more time to finish adding more basic tests cases.

Thoughts ?


Thanks!

**Comment by amarts** [comment]
Lets just add it to repo now (for 0.4 version). Lets add it into RPM before the next version, along with few more tools which we feel are opt for debugging.

**Comment by pkalever** [comment]
> Lets just add it to repo now (for 0.4 version). Lets add it into RPM before the next version, along with few more tools which we feel are opt for debugging.

Cool, thanks!

**Comment by pkalever** [comment]
Updated tags, ready for merge. Thanks!

**Pull request merged**
