### PR TITLE
NEWS: update

### PR DESCRIPTION
**Pull request by pkalever**
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@amarts @lxbsz as discussed, lets merge this PR and tag a release.

I will wait for your acks here (I already got one from amar offline) to see if there is anything that we should wait for before tagging.

Thanks!

**Comment by lxbsz** [comment]
> @amarts @lxbsz as discussed, lets merge this PR and tag a release.
> 
> I will wait for your acks here (I already got one from amar offline) to see if there is anything that we should wait for before tagging.
> 
@pkalever 

Yeah, I did it already :-).

Didn't you see it above?

Thanks.

**Comment by pkalever** [comment]
@lxbsz I need an ack about making a release, not for this PR merge.

To be specific about my question,
- Can we make a release now ?
- Is there anything that you would like to include in this v0.4 release ?

If we are all good, I will merge this and Tag v0.4

Thanks!

**Comment by lxbsz** [comment]
> @lxbsz I need an ack about making a release, not for this PR merge.
> 
> To be specific about my question,
> 

@pkalever 
Ah, okay, sorry for misunderstanding.

> * Can we make a release now ?
Yeah, sure.

> * Is there anything that you would like to include in this v0.4 release ?
> 
All look good to me for the next v0.4 release.
Nothing new from my side now.

> If we are all good, I will merge this and Tag v0.4
> 
Sure.
Thanks.
BRs

> Thanks!

**Comment by pkalever** [comment]
Thanks @amarts @lxbsz for the acks. Merging this now.

**Pull request merged**
