### PR TITLE
create: fix failing with io_timeout not support

### PR DESCRIPTION
**Pull request by lxbsz**
### What does this PR achieve? Why do we need it?
If the configshell version is low, even we do not specify the
io-timeout options, it will fail, but the exepcting should just
skip it.

### Does this PR fix issues?

Fixes: #

### CODE REVIEW

**Comment by pkalever** [comment]
@lxbsz can you please elaborate the commit-msg, sorry but its bit unclear for me.

**Comment by pkalever** [comment]
@lxbsz may be an example output of behavior with this patch and without this patch in the commit-msg will help.

**Comment by lxbsz** [comment]
> @lxbsz may be an example output of behavior with this patch and without this patch in the commit-msg will help.

Sure, will update it.

**Comment by lxbsz** [comment]
@pkalever 
Updated the tag.
Thanks.

**Comment by pkalever** [comment]
Merged now, thanks @lxbsz

**Pull request merged**
