### PR TITLE
Saveconfig fixes

### PR DESCRIPTION
**Pull request by pkalever**
* delete: add a way to saveconfig with delete operation
* modify: return fail if block is not loaded

### CODE REVIEW

**Comment by pkalever** [comment]
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1585204
Depends on: targetcli#117 rtslib#132

**Comment by pkalever** [comment]
@pranithk @lxbsz please take a look.

**Comment by lxbsz** [comment]
@pkalever 
Test and it works:

The old logs:
# journalctl -r
-- Logs begin at Sun 2018-06-03 23:35:13 EDT, end at Mon 2018-06-04 00:46:13 EDT. --
Jun 04 00:46:13 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:45:50 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:45:41 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:41:22 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:39:58 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:38:33 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block1
Jun 04 00:11:03 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block0
Jun 04 00:10:06 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block0
Jun 04 00:07:31 gblock2 gluster-blockd[1270]: No such path /backstores/user:glfs/block0
...

**Comment by pkalever** [comment]
@lxbsz Thanks for testing this.

**Comment by pkalever** [comment]
@lxbsz @pranithk 
Yay!! We have the dependent targetcli and rtslib patches upstream now.

**Comment by pranithk** [comment]
There could be some more problems of this sort, that we will find and fix as part of https://github.com/gluster/gluster-block/issues/87

**Pull request merged**
