### PR TITLE
doc: remove PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by pkalever**
As we want to start allowing reviews on github, let us remove the msg
mentioning "gluster-block does not use GitHub Pull-Requests" from
.github/PULL_REQUEST_TEMPLATE

Change-Id: Ia051926c5a185a030569bb5ea3aa9eff105d94a8
Fixes: #50
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
Please review: @pranithk @lxbsz @vbellur @nixpanic

**Comment by nixpanic** [comment]
Should be fine, but maybe you want to add a `CONTRIBUTING.md` file?

**Comment by pkalever** [comment]
> Should be fine, but maybe you want to add a CONTRIBUTING.md file?
Yes that is a good idea, I think we should have a basic template for ISSUE_TEMPLATE.md as well.

Thanks @nixpanic.

**Comment by vbellur** [comment]
Looks good to me!

**Comment by vbellur** [comment]
@pkalever Please open a new pull request for the changes suggested.

**Pull request merged**
