### PR TITLE
readme: add libtirpc-devel rpcgen as perrequesites

### PR DESCRIPTION
**Pull request by pkalever**
depends on PR#57

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@nigelbabu That's a good idea. I will make the changes to reflect your suggestion.

Thanks!

**Comment by obnoxxx** [comment]
My problem is that it does not build on F28. You can install libtirpc-devel and rpc-gen, but it fails complaining it does not find <rpc/rpc.h>:

```
make  all-recursive
make[1]: Entering directory '/data/obnox/devel/gluster/gluster-block'
Making all in rpc
make[2]: Entering directory '/data/obnox/devel/gluster/gluster-block/rpc'
Making all in rpcl
make[3]: Entering directory '/data/obnox/devel/gluster/gluster-block/rpc/rpcl'
make  all-am
make[4]: Entering directory '/data/obnox/devel/gluster/gluster-block/rpc/rpcl'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H      -g -O2 -MT block_clnt.lo -MD -MP -MF .deps/block_clnt.Tpo -c -o block_clnt.lo block_clnt.c
libtool: compile:  gcc -DHAVE_CONFIG_H -g -O2 -MT block_clnt.lo -MD -MP -MF .deps/block_clnt.Tpo -c block_clnt.c  -fPIC -DPIC -o .libs/block_clnt.o
In file included from block_clnt.c:7:
block.h:9:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by pkalever** [comment]
@amarts @lxbsz please review. Thanks!

**Comment by pkalever** [comment]
Thanks @amarts, merging now.

**Pull request merged**
