### PR TITLE
resize: retry doesn't care about all nodes status

### PR DESCRIPTION
**Pull request by pkalever**
### What does this PR achieve? Why do we need it?

Problem:
-------
If modify size fails on one node, after fixing the issue a retry with
should fix the configuration on previously failed node. But retrying modify size
is bailing out.

This is a side effect caused with our recent changes made with
'resize: update the size in metafile soon after ResizeEntry'

$ gluster-block modify sample/block1 size 2MiB
IQN: iqn.2016-12.org.gluster-block:02268663-117e-4c19-a9df-e11a5ba42715
FAILED ON:  192.168.124.172
SUCCESSFUL ON:  192.168.124.121 192.168.124.40
RESULT: FAIL

After fixing 192.168.124.172, retrying modify gives below
error:

$ gluster-block modify sample/block1 size 2MiB
request size (2.0 MiB) is same as current size (2.0 MiB) ]
RESULT:FAIL

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
Thanks for the review @lxbsz , May I request your test ack on this please?

**Comment by lxbsz** [comment]
sure will test.

**Comment by lxbsz** [comment]
It failed.
```
# gluster-block modify repvol/block0 size 3G
request size (3.0 GiB) is same as current size (3.0 GiB) ]
RESULT:FAIL
# 
```

**Comment by lxbsz** [comment]
> It failed.
> 
> ```
> # gluster-block modify repvol/block0 size 3G
> request size (3.0 GiB) is same as current size (3.0 GiB) ]
> RESULT:FAIL
> # 
> ```

My test steps was not correct and now it works for me:

```
1 VOLUME: repvol
  2 GBID: 0f9483be-31a1-4ecb-8e3a-6137bedc6217
  3 HA: 1
  4 ENTRYCREATE: INPROGRESS
  5 PRIOPATH: 10.72.36.245
  6 SIZE: 1073741824
  7 RINGBUFFER: 0
  8 BLKSIZE: 0
  9 IOTIMEOUT: 0
 10 ENTRYCREATE: SUCCESS
 11 10.72.36.245: CONFIGINPROGRESS
 12 10.72.36.245: CONFIGSUCCESS
 13 SIZE: 2147483648
 14 10.72.36.245: RSINPROGRESS-2147483648
 15 10.72.36.245: RSSUCCESS-2147483648
 16 SIZE: 3221225472
 17 10.72.36.245: RSFAIL                                                                                                                   
 18 SIZE: 3221225472
 19 10.72.36.245: RSINPROGRESS-3221225472
 20 10.72.36.245: RSSUCCESS-3221225472
```

**Comment by pkalever** [comment]
@lxbsz thanks, updated the tags. Merging now.

**Pull request merged**
