### PR TITLE
Fix memleak for errMsg

### PR DESCRIPTION
**Pull request by lxbsz**
Signed-off-by: Xiubo Li <xiubli@redhat.com>

### CODE REVIEW

**Comment by lxbsz** [comment]
@pkalever @amarts Please review, thanks.

**Comment by pkalever** [comment]
@lxbsz please rebase this PR. Thanks!

**Comment by lxbsz** [comment]
> @lxbsz please rebase this PR. Thanks!

Done, thanks.

**Comment by pkalever** [comment]
Merged now. Thanks @lxbsz

**Pull request merged**
