### PR TITLE
Snapcraft package

### PR DESCRIPTION
**Pull request by cholcombe973**
This is the beginning of a snapcraft package for gluster-block.  It is currently missing targetcli and tcmu-runner.  This should allow gluster-block to deployed on many more platforms.

### CODE REVIEW

**Comment by nixpanic** [comment]
Hi @cholcombe973,

What is the use when targetcli and tcmu-runner are not available? I'm not familiar with Snapcraft, so I might be missing some basic understanding.

Thanks,
Niels

**Comment by cholcombe973** [comment]
That's a really good question.  I think the answer is it's useless without
targetcli and tcmu-runner.  I started working on amending my PR but I never
got around to finishing it.  Snapcraft is basically an easy way to package
your software so you can deploy it across many different linux platforms.
Looks like centos is in progress: https://snapcraft.io/docs/core/install

**Comment by nixpanic** [comment]
Thanks for the answer! I think we can hold off with merging this until
tcmu-runner and targetcli are available too. Or, maybe add some TODO
comments in the file so that it is clear what still is pending.

Also, you probably should use `configure.ac` to create this from a `.in`
file, that way the version can be automatically replaced (see the
`.spec.in` for an example of `@PACKAGE_VERSION@`).

I'm not sure if @pkalever accepts GitHub pull requests, some of the
other patches have been reviewed+merged through Gerrit at
https://review.gluster.org/

**Comment by pkalever** [comment]
This seems quite old now, feel free to open a new PR based on master. Thanks!

**Pull request closed without merging**
