### PR TITLE
Make USER field available in Block Info.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
It was an intentional :-)
The GBID is username in "gluster-block info" response.
so we don't want to duplicate GBID and USERNAME. 

Thanks for the effort though.

**Comment by humblec** [comment]
@pkalever Auth enable reflect a new `USERNAME` field, why its so then? Also, how come one can assume "GBID" is the `USERNAME` from just looking at the `info` response?

**Comment by pkalever** [comment]
I personally don't like to see duplicated fields in the info.
May be we can do below,
1. document GBID uses filename, username, wwid, iqn postfix ...
2. when auth is enable s/GBID/USERNAME/
3. In the worst case, we can print like "GBID/USERNAME: bla bla bla bla"

the order is w.r.t my choice, point 1 is most preferable.

@vbellur @pranithk Thoughts ?

**Comment by humblec** [comment]
@pkalever I can adjust the patch to `2 or 3`. I think making `USERNAME` visible is valid in the outputs. Will wait for others opinion as well, before sending next version.

**Comment by humblec** [comment]
@vbellur any thoughts ?

**Comment by pranithk** [comment]
3rd option looks good to me.

**Comment by vbellur** [comment]
3rd option looks good to me too, thanks!

**Comment by pkalever** [comment]
@humblec  Please make the changes to reflect 3rd option and submit to our gerrit repository, as we are not ready for github yet.

The Current repository that we are using is gerrit, merging your changes with github will reflect into origin and these are all together different repos.

**Comment by pkalever** [comment]
@humblec do you have plans to work on this soon ?

**Comment by pkalever** [comment]
Please reopen this, if needed.

**Pull request closed without merging**
