### PR TITLE
Fix gluster master build

### LINKED ISSUE #75: Use correct gfapi function signatures
This issue came up while installing gluster-block on top of glusterfs 4.1dev. 
The gfapi functions have changed as per the discussion https://github.com/gluster/glusterfs/issues/389# but some gfapi calls inside gluster-block are not updated and are still using the old apis. 
Therefore, update the below functions to use the changed gfapi.

- [ ] glfs_ftruncate

### PR DESCRIPTION
**Pull request by amarts**
Fixes #75 

Also overrides #77 as I had to push one more patch to get the build properly done.

### CODE REVIEW

**Comment by pkalever** [comment]
@amarts @bhumikagoyal IMO, Guster API (gfapi) shouldn't break the backward compatibility.
This will break all the application, such as qemu, tcmu, samba, gluster-block ... and many more.

IMHO, the fix should go in glusterfs.

Thanks!

**Comment by lxbsz** [comment]
Yeah, agree with Prasanna. And we couldn't assume that only the gluster-block project is using the gfapi.

**Comment by pkalever** [comment]
As this is agreed by everyone in the team, probably we should close it.

@amarts feel free to close it accordingly.

**Comment by amarts** [comment]
> As this is agreed by everyone in the team, probably we should close it.
> 
> @amarts feel free to close it accordingly.

I agree that the 'ideal' fix is glusterfs not changing anything, but as this project depends on the changes done in glusterfs project, safe-guarding the project with a proper version check is not at all a bad option, rather the right way to go.

**Comment by amarts** [comment]
As per the discussions in gluster/glusterfs#539 we need to handle the version number properly in gluster-block project itself. Lets continue reviewing and get this going!

**Comment by amarts** [comment]
@pkalever @lxbsz please take a look. This is important for keeping the project up-to-date with glusterfs-master branch, and there may be more changes. But as it doesn't break anything in existing code, I would prefer to have it. 

If you notice, without this, we are building the project with glusterfs-5.1.x right now in our nightly builds here: https://ci.centos.org/view/Gluster/job/gluster_block_basic/21/console. Ideal is to build it everyday with glusterfs master from previous night. With this patch, we can achieve that.

**Comment by lxbsz** [comment]
> @pkalever @lxbsz please take a look. This is important for keeping the project up-to-date with glusterfs-master branch, and there may be more changes. But as it doesn't break anything in existing code, I would prefer to have it.
> 
> If you notice, without this, we are building the project with glusterfs-5.1.x right now in our nightly builds here: https://ci.centos.org/view/Gluster/job/gluster_block_basic/21/console. Ideal is to build it everyday with glusterfs master from previous night. With this patch, we can achieve that.

Is it possible that in future the API will be updated again, like this ?

If so IMO it will be better that to use a macro that has the version number instead of GLUSTERFS_NOT_NEW, something like GLUSTERFS_VERSION_5_1_X. Will this make sense here ?

Thanks.

**Comment by amarts** [comment]
> something like GLUSTERFS_VERSION_5_1_X. Will this make sense here ?

Agree! We can do something like that.

**Comment by pkalever** [comment]
Fixed by: #178

**Pull request closed without merging**
