### PR TITLE
systemd: clear the target config only when tcmu-runner is running

### PR DESCRIPTION
**Pull request by pkalever**
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
Credits to @lxbsz for debugging along.

@nixpanic
Requirement is we need to run targetctl clear only when tcmu-runner is running. I need your opinion at this changes. Do you foresee any issues with this hack ? Thanks!

**Comment by nixpanic** [comment]
On Mon, Oct 15, 2018 at 07:19:25AM -0700, Prasanna Kumar Kalever wrote:
> @nixpanic
> Requirement is we need to run targetctl clear only when tcmu-runner is running. I need your opinion at this changes. Do you foresee any issues with this hack ? Thanks!

As briefly discussed and further explained on IRC, it looks good to me.

**Comment by lxbsz** [comment]
> @lxbsz I have changed something after your last tested it. Please retest. Thanks!

Yeah, Prasanna, this works for me.

**Comment by pkalever** [comment]
Thanks @lxbsz for the review and test.
Have updated the tags, merging now.

**Pull request merged**
