### PR TITLE
modify: misc fix for the logs

### PR DESCRIPTION
**Pull request by lxbsz**
### What does this PR achieve? Why do we need it?
Fix the code style and some strange logs output.
such as it will be look like: 
"... block_volume/block_volume ..."
"... on volume (null) ..."

### Does this PR fix issues?

No issue about this.

### CODE REVIEW

**Comment by lxbsz** [comment]
@pkalever @amarts 
Please review, thanks.

**Comment by pkalever** [comment]
@lxbsz please update the tags, this is ready to land. Thanks!

**Comment by lxbsz** [comment]
@pkalever 
Done.
Thanks.

**Comment by pkalever** [comment]
> @pkalever
> Done.

I'm not Signed-off-by :-)
Please change it to Reviewed-by:

**Comment by lxbsz** [comment]
@pkalever 
Done.

**Comment by pkalever** [comment]
@lxbsz Thanks!

**Pull request merged**
