### PR TITLE
Don't let LOG segfault if log dir does not exist - fall back to stderr.

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@pkalever  PTAL

**Comment by raghavendra-talur** [comment]
Looks good to me

**Comment by obnoxxx** [comment]
https://review.gluster.org/17614

and to gerrit it goes...

**Comment by pkalever** [comment]
This git merged from gerrit.

**Comment by pkalever** [comment]
Thanks @obnoxxx

**Pull request closed without merging**
