### PR TITLE
daemon: change minimum rhel kernel version to 3.10.0-862.14.4

### PR DESCRIPTION
**Pull request by pkalever**
change kernel version
from 3.10.0-862.11.1 (RHEL-7.5.3) to 3.10.0-862.14.4 (RHEL-7.5.4)

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
> But due to overlap of variable name (out) and label (out), was bit confused... While compiler can distinguish between them, would be good to keep them separate for easier reviews (in future).

@amarts why next ? lets address it here, right now. This is a simple fix, will update the PR soon. Thanks!

**Comment by pkalever** [comment]
@amarts @lxbsz updated the PR, please take a look. Thanks!

**Comment by pkalever** [comment]
> Build the code okay ...

@lxbsz You don't have to :-)

There is a Travis CI running now, Explore "All Checks have passed" section above, you should get to see build log at https://travis-ci.com/gluster/gluster-block/builds/89264648 (for my previous change)

Thanks to @obnoxxx for making this possible :+1:

**Comment by lxbsz** [comment]
> > Build the code okay ...
> 
> @lxbsz You don't have to :-)
> 
> There is a Travis CI running now, Explore "All Checks have passed" section below, you should get to see build log at https://travis-ci.com/gluster/gluster-block/builds/89264648 (for my previous change)
> 
> Thanks to @obnoxxx for making this possible 👍

That's cool. 👍

**Comment by pkalever** [comment]
Thanks @lxbsz & @amarts, have updated the tags. Will merge this post CI check completes.

**Pull request merged**
