### PR TITLE
docs: create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pkalever**
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@lxbsz @amarts Please review and help with suggestions.

you can have a glace about how it looks like, here:
https://github.com/pkalever/gluster-block/blob/contributing-pr/CONTRIBUTING.md

Thanks!

**Comment by lxbsz** [comment]
@pkalever 
BTW, should we mention that if adding new features, should the test cases be added at the same time ?
Thanks.

**Comment by pkalever** [comment]
> BTW, should we mention that if adding new features, should the test cases be added at the same time ?

Good thought, let me add it to the doc. Thanks @lxbsz !

**Comment by pkalever** [comment]
Cannot make changes to this branch, I pushed this with github UI. Opening #196 for dealing with this. Thanks!

**Pull request closed without merging**
