### PR TITLE
docs: add ISSUE and PR TEMPLATE

### PR DESCRIPTION
**Pull request by pkalever**
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@amarts @lxbsz Please suggest if we need any more details as such. Thanks!

**Comment by lxbsz** [comment]
@pkalever BTW, why host this in .github/ ?

**Comment by pkalever** [comment]
@lxbsz see:
https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository

**Comment by lxbsz** [comment]
> @lxbsz see:
> https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository

Cool. Looks good to me.

**Comment by pkalever** [comment]
Updated tags, ready for merge.

**Pull request merged**
