### PR TITLE
travis: build on f27, f28, f29 and centos7

### PR DESCRIPTION
**Pull request by pkalever**
### What does this PR achieve? Why do we need it?
Add Travis builds for:
* Fedora 28
* Fedora 29
* Centos 7

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by amarts** [comment]
Lets remove F28 now that it works on F29 and CentOS7.

**Comment by pkalever** [comment]
@amarts but F28 is not EOL yet.

do you still think, checking build on latest version of fedora and centos is enough for us ?

**Comment by amarts** [comment]
I think one cutting edge (latest fedora) and one stable (centos latest-7) is good enough. More is fine, but we may not get anything specific because of testing in more similar platforms anyways.

**Comment by pkalever** [comment]
@amarts if so, should we have to remove build for F27 (tests glibc way on fedora) too ?

Centos-7 anyway build with glibc only.

**Comment by amarts** [comment]
Yes please, remove f27 too.

**Comment by pkalever** [comment]
> Yes please, remove f27 too.

@amarts sure. Just re-triggered the build on F27 (along with F28, F29 and centos7) one last time, to makesure that the recent merged patches won't cause regression on F27. Once the build finishes. I will refresh this PR addressing your review. Thanks!

**Comment by pkalever** [comment]
> > Yes please, remove f27 too.
> 
> @amarts sure. Just re-triggered the build on F27 (along with F28, F29 and centos7) one last time, to makesure that the recent merged patches won't cause regression on F27. Once the build finishes. I will refresh this PR addressing your review. Thanks!

Build is successful on F27/F28/F29 and Centos-7:
https://travis-ci.com/gluster/gluster-block/builds/108321728

Will refresh the PR soon to reflect the review.

**Comment by pkalever** [comment]
Thanks for the review @amarts and @lxbsz.

**Pull request merged**
