### PR TITLE
replace-node: update PRIOPATH at metadata when it match with old-node

### PR DESCRIPTION
**Pull request by pkalever**
if the PRIOPATH and old-node are the same then update PRIOPATH at metadata
with the new-node. Also defend the same at create activity as part of
replace node operation.

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
@pranithk thanks for reminding me about this.

@lxbsz @pranithk @amarts please review. Thanks in advance.

**Comment by pkalever** [comment]
@lxbsz did you test this ? Does it work ? Thanks!

**Comment by pkalever** [comment]
@lxbsz please review and help test this.

- V2:

diff --git a/rpc/block_svc_routines.c b/rpc/block_svc_routines.c
index 4cd3869..9970e00 100644
--- a/rpc/block_svc_routines.c
+++ b/rpc/block_svc_routines.c
@@ -2465,11 +2465,10 @@ block_replace_cli_1_svc_st(blockReplaceCli *blk, struct svc_req *rqstp)
   if (savereply && savereply->force && savereply->dop->status) {
     GB_METAUPDATE_OR_GOTO(lock, glfs,  blk->block_name,  blk->volume,
                           errCode, errMsg, out, "%s: CLEANUPSUCCESS\n", blk->old_node);
-
-    if (info->prio_path[0] && !strcmp(info->prio_path, blk->old_node)) {
-        GB_METAUPDATE_OR_GOTO(lock, glfs, blk->block_name, blk->volume,
-                              errCode, errMsg, out, "PRIOPATH: %s\n", blk->new_node);
-    }
+  }
+  if (info->prio_path[0] && !strcmp(info->prio_path, blk->old_node)) {
+    GB_METAUPDATE_OR_GOTO(lock, glfs, blk->block_name, blk->volume,
+        errCode, errMsg, out, "PRIOPATH: %s\n", blk->new_node);
   }
 
   errCode = 0;
(END)

**Comment by lxbsz** [comment]
Sorry Prasanna, I missed this notification:

Create one target block HA=2 in node rhel1 and rhel2, then rhel3 upgrade the tcmu-runner and package to the newest version and upstream version, relpace the rhel2 with rhel3:

```
[root@rhel2 gluster-block]# rpm -qa|grep -e gluster-block -e tcmu 
libtcmu-1.2.0-16.el7rhgs.x86_64
tcmu-runner-1.2.0-16.el7rhgs.x86_64
gluster-block-0.2.1-15.el7rhgs.x86_64
[root@rhel2 tcmu-runner]# gluster-block create dht/block0 ha 2 prealloc full 192.168.195.162,192.168.195.163 1G
IQN: iqn.2016-12.org.gluster-block:6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e
PORTAL(S):  192.168.195.162:3260 192.168.195.163:3260
RESULT: SUCCESS

[root@rhel2 ~]# targetcli ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:glfs .............................................................................................. [Storage Objects: 1]
  |   o- block0 .......................... [dht@192.168.195.162/block-store/6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e (1.0GiB) activated]
  |     o- alua ................................................................................................... [ALUA Groups: 1]
  |       o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.2016-12.org.gluster-block:6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e ................................................ [TPGs: 2]
  |   o- tpg1 .................................................................................................. [gen-acls, no-auth]
  |   | o- acls .......................................................................................................... [ACLs: 0]
  |   | o- luns .......................................................................................................... [LUNs: 1]
  |   | | o- lun0 ................................................................................. [user/block0 (default_tg_pt_gp)]
  |   | o- portals .................................................................................................... [Portals: 1]
  |   |   o- 192.168.195.162:3260 ............................................................................................. [OK]
  |   o- tpg2 ........................................................................................................... [disabled]
  |     o- acls .......................................................................................................... [ACLs: 0]
  |     o- luns .......................................................................................................... [LUNs: 1]
  |     | o- lun0 ................................................................................. [user/block0 (default_tg_pt_gp)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 192.168.195.164:3260 ............................................................................................. [OK]
  o- loopback ......................................................................................................... [Targets: 0]
[root@rhel2 ~]# 
[root@rhel2 gluster-block]# 


[root@rhel3 gluster-block]# rpm -qa|grep -e tcmu 
libtcmu-1.2.0-25.el7rhgs.x86_64
tcmu-runner-1.2.0-25.el7rhgs.x86_64
[root@rhel3 gluster-block]# 
[root@rhel3 gluster-block]# gluster-block --version
gluster-block (0.2.1)
Repository rev: https://github.com/gluster/gluster-block.git
Copyright (c) 2016 Red Hat, Inc. <https://redhat.com/>
gluster-block comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
[root@rhel3 gluster-block]# which gluster-blockd gluster-block
/usr/local/sbin/gluster-blockd
/usr/local/sbin/gluster-block
[root@rhel3 tcmu-runner]# gluster-block replace dht/block0 192.168.195.163 192.168.195.164 
NAME: block0
CREATE SUCCESS: 192.168.195.164
DELETE SUCCESS: 192.168.195.163
REPLACE PORTAL SUCCESS ON:  192.168.195.162
RESULT: SUCCESS

[root@rhel3 tcmu-runner]# targetcli ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:glfs .............................................................................................. [Storage Objects: 1]
  | | o- block0 .......................... [dht@192.168.195.164/block-store/6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e (1.0GiB) activated]
  | |   o- alua ................................................................................................... [ALUA Groups: 3]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | |     o- glfs_tg_pt_gp_ano .................................................................. [ALUA state: Active/non-optimized]
  | |     o- glfs_tg_pt_gp_ao ....................................................................... [ALUA state: Active/optimized]
  | o- user:qcow .............................................................................................. [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.2016-12.org.gluster-block:6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e ................................................ [TPGs: 2]
  |   o- tpg1 .................................................................................................. [gen-acls, no-auth]
  |   | o- acls .......................................................................................................... [ACLs: 0]
  |   | o- luns .......................................................................................................... [LUNs: 1]
  |   | | o- lun0 ................................................................................ [user/block0 (glfs_tg_pt_gp_ano)]
  |   | o- portals .................................................................................................... [Portals: 1]
  |   |   o- 192.168.195.164:3260 ............................................................................................. [OK]
  |   o- tpg2 ........................................................................................................... [disabled]
  |     o- acls .......................................................................................................... [ACLs: 0]
  |     o- luns .......................................................................................................... [LUNs: 1]
  |     | o- lun0 ................................................................................. [user/block0 (glfs_tg_pt_gp_ao)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 192.168.195.162:3260 ............................................................................................. [OK]
  o- loopback ......................................................................................................... [Targets: 0]
[root@rhel3 tcmu-runner]# 

```
Then upgrade the rhel2's package to the newest version and replace rhel3 with rhel2:

```
[root@rhel3 tcmu-runner]# gluster-block replace dht/block0 192.168.195.164 192.168.195.163 
NAME: block0
CREATE SUCCESS: 192.168.195.163
DELETE SUCCESS: 192.168.195.164
REPLACE PORTAL SKIPPED ON:  192.168.195.162
RESULT: SUCCESS

[root@rhel3 tcmu-runner]# 


[root@rhel2 ~]# targetcli ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:glfs .............................................................................................. [Storage Objects: 1]
  |   o- block0 .......................... [dht@192.168.195.163/block-store/6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e (1.0GiB) activated]
  |     o- alua ................................................................................................... [ALUA Groups: 3]
  |       o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  |       o- glfs_tg_pt_gp_ano .................................................................. [ALUA state: Active/non-optimized]
  |       o- glfs_tg_pt_gp_ao ....................................................................... [ALUA state: Active/optimized]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.2016-12.org.gluster-block:6c3ae32a-f6e4-455f-bd7c-772d9d1a9a1e ................................................ [TPGs: 2]
  |   o- tpg1 .................................................................................................. [gen-acls, no-auth]
  |   | o- acls .......................................................................................................... [ACLs: 0]
  |   | o- luns .......................................................................................................... [LUNs: 1]
  |   | | o- lun0 ................................................................................ [user/block0 (glfs_tg_pt_gp_ano)]
  |   | o- portals .................................................................................................... [Portals: 1]
  |   |   o- 192.168.195.163:3260 ............................................................................................. [OK]
  |   o- tpg2 ........................................................................................................... [disabled]
  |     o- acls .......................................................................................................... [ACLs: 0]
  |     o- luns .......................................................................................................... [LUNs: 1]
  |     | o- lun0 ................................................................................. [user/block0 (glfs_tg_pt_gp_ao)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 192.168.195.162:3260 ............................................................................................. [OK]
  o- loopback ......................................................................................................... [Targets: 0]
[root@rhel2 ~]# 

```


Tested-by: Xiubo Li xiubli@redhat.com

**Comment by pkalever** [comment]
Tags Updated Merging this PR. Thanks @lxbsz for review and testing it.

**Pull request merged**
